server:
  port: 8080

spring:
  profiles:
    active:
      - local
    group:
      local:
        - db-local
        - site-local
      dev:
        - db-dev
      test:
        - db-test
        - site-test
    include:
      - db
      - site


